apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/kube-default: true
    app: jenkins
    component: agent
spec:
  containers:
  - name: ci-container
    image: quyen/clean-architecture-nodejs-pattern
    imagePullPolicy: Always
    tty: true
  # - name: docker-dind-awscli
  #   image: docker-dind-awscli
  #   imagePullPolicy: IfNotPresent
  #   securityContext:
  #     privileged: true
  #   volumeMounts:
  #     - name: dind-storage
  #       mountPath: /var/lib/docker
  # - name: helm-awscli
  #   image: helm-awscli
  #   imagePullPolicy: IfNotPresent
  #   volumeMounts:
  #     - name: k8s-kubeconfig
  #       mountPath: /root/.kube/
  #       readOnly: true
  # volumes:
  #   - name: dind-storage
  #     emptyDir: {}
  #   - name: k8s-kubeconfig
  #     configMap:
  #       name: k8s-kubeconfig-configmap